import {
  FileText,
  Scissors,
  Combine,
  Minimize2,
  FileImage,
  FileType2,
  Image as ImageIcon,
  Crop,
  Eraser,
  Palette,
  Type,
  AlignLeft,
  Hash,
  Sparkles,
  Archive,
  FileArchive,
  RefreshCw,
  Brain,
  ScanText,
  BookOpen,
  Braces,
  Binary,
  Link2,
  KeyRound,
  StickyNote, Clipboard, ListChecks, QrCode, Columns, Clock,
  Lock, Shield, Key, Database, Table, Percent, Activity, Search, GitBranch
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type ToolCategory =
  | "documents"
  | "images"
  | "text"
  | "files"
  | "ai"
  | "developer"
  | "productivity"
  | "data"
  | "reference";

export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: ToolCategory;
  tint: "rust" | "moss" | "clay" | "ink";
  implemented?: boolean;
  acceptsFileType?: string;
}

export const categories: { id: ToolCategory; label: string; blurb: string }[] =
  [
    { id: "documents", label: "Documents", blurb: "PDFs, Word, Excel" },
    { id: "images", label: "Images", blurb: "Resize, convert, clean" },
    { id: "text", label: "Text", blurb: "Edit, count, transform" },
    { id: "files", label: "Files", blurb: "Convert, archive" },
    { id: "ai", label: "AI", blurb: "Summarize, extract" },
    { id: "developer", label: "Developer", blurb: "Encode, format" },
    { id: "productivity", label: "Productivity", blurb: "Notes, lists" },
    { id: "data", label: "Data", blurb: "CSV, SQL, JSON" },
    { id: "reference", label: "Reference", blurb: "HTTP, entities, cheat sheets" },
  ];

export const tools: Tool[] = [
  // Documents
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine PDFs in the order you want.",
    icon: Combine,
    category: "documents",
    tint: "rust",
    implemented: true,
    acceptsFileType: "application/pdf",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Pull pages out of a PDF into new files.",
    icon: Scissors,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce file size while keeping quality.",
    icon: Minimize2,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "pdf-to-image",
    name: "PDF → Image",
    description: "Convert each page to JPG or PNG.",
    icon: FileImage,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "word-to-pdf",
    name: "Word → PDF",
    description: "Export .docx to a clean PDF.",
    icon: FileType2,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "excel-to-pdf",
    name: "Excel → PDF",
    description: "Render spreadsheets as PDFs.",
    icon: FileText,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "pdf-to-word",
    name: "PDF → Word",
    description: "Convert PDFs back to .docx.",
    icon: FileType2,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "pdf-to-excel",
    name: "PDF → Excel",
    description: "Extract tables into spreadsheets.",
    icon: FileText,
    category: "documents",
    tint: "rust",
    implemented: true,
  },

  // Images
  {
    slug: "image-resize",
    name: "Resize image",
    description: "Set new width and height in pixels.",
    icon: Crop,
    category: "images",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "image-compress",
    name: "Compress image",
    description: "Lossy compression with a quality slider.",
    icon: Minimize2,
    category: "images",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "image-convert",
    name: "Convert format",
    description: "Switch between JPG, PNG, and WebP.",
    icon: RefreshCw,
    category: "images",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "remove-background",
    name: "Remove background",
    description: "Clean cutouts using on-device AI.",
    icon: Eraser,
    category: "images",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "image-palette",
    name: "Extract palette",
    description: "Pull dominant colors from any image.",
    icon: Palette,
    category: "images",
    tint: "moss",
    implemented: true,
  },

  // Text
  {
    slug: "case-converter",
    name: "Case converter",
    description: "UPPER, lower, Title, camelCase…",
    icon: Type,
    category: "text",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "word-counter",
    name: "Word counter",
    description: "Words, characters, reading time.",
    icon: Hash,
    category: "text",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "text-cleanup",
    name: "Text cleanup",
    description: "Strip extra spaces, line breaks, tabs.",
    icon: AlignLeft,
    category: "text",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "text-to-latex",
    name: "Text → LaTeX",
    description: "Safely escape text for LaTeX.",
    icon: BookOpen,
    category: "text",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "summarizer",
    name: "Summarizer",
    description: "Condense long passages to key points.",
    icon: Sparkles,
    category: "text",
    tint: "clay",
    implemented: true,
  },

  // Files
  {
    slug: "file-convert",
    name: "File converter",
    description: "Convert across common file formats.",
    icon: RefreshCw,
    category: "files",
    tint: "ink",
  },
  {
    slug: "zip-files",
    name: "Zip files",
    description: "Bundle a folder into a single archive.",
    icon: Archive,
    category: "files",
    tint: "ink",
    implemented: true,
  },
  {
    slug: "unzip",
    name: "Unzip",
    description: "Extract files from any .zip archive.",
    icon: FileArchive,
    category: "files",
    tint: "ink",
    implemented: true,
  },

  // AI
  {
    slug: "ai-summarize",
    name: "AI summary",
    description: "Document → key bullets in seconds.",
    icon: Brain,
    category: "ai",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "ocr",
    name: "OCR",
    description: "Pull text out of scans and photos.",
    icon: ScanText,
    category: "ai",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "extract-content",
    name: "Content extractor",
    description: "Get clean article text from any URL.",
    icon: BookOpen,
    category: "ai",
    tint: "rust",
    implemented: true,
  },

  // Developer
  {
    slug: "json-format",
    name: "JSON formatter",
    description: "Pretty print, validate, minify.",
    icon: Braces,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "base64",
    name: "Base64",
    description: "Encode and decode Base64 strings.",
    icon: Binary,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "url-encode",
    name: "URL encoder",
    description: "Encode and decode URL components.",
    icon: Link2,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "uuid",
    name: "UUID generator",
    description: "Create random v4 UUIDs.",
    icon: KeyRound,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "qr-generator",
    name: "QR Generator",
    description: "Create QR codes for text, URLs, and WiFi.",
    icon: QrCode,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description: "Compare two pieces of text side by side.",
    icon: Columns,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "unix-timestamp",
    name: "Unix Timestamp",
    description: "Convert between Epoch time and dates.",
    icon: Clock,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Write and preview markdown in real-time.",
    icon: FileText,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Create MD5, SHA-1, SHA-256 hashes.",
    icon: Shield,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Inspect header and payload of any token.",
    icon: Key,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "regex-tester",
    name: "RegEx Tester",
    description: "Build and test regular expressions.",
    icon: Search,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "base64-image",
    name: "Base64 Image",
    description: "Convert images to Data URI strings.",
    icon: FileImage,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert HEX, RGB, HSL, and LCH.",
    icon: Palette,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "bcrypt-generator",
    name: "Bcrypt Generator",
    description: "Hash passwords with bcrypt securely.",
    icon: Shield,
    category: "developer",
    tint: "moss",
    implemented: true,
  },

  // Productivity
  {
    slug: "notes",
    name: "Quick notes",
    description: "Local notes that stay between visits.",
    icon: StickyNote,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "todo",
    name: "To-do",
    description: "A simple list. Nothing in the way.",
    icon: ListChecks,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "clipboard",
    name: "Clipboard history",
    description: "Stash snippets you reach for often.",
    icon: Clipboard,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "password-gen",
    name: "Password Generator",
    description: "Create secure, random passwords.",
    icon: Lock,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Generate placeholder text for layouts.",
    icon: FileText,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert between common units of measure.",
    icon: RefreshCw,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "percentage-calc",
    name: "Percentage Calculator",
    description: "Quickly calculate percentages and growth.",
    icon: Percent,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  // Data
  {
    slug: "csv-json",
    name: "CSV ↔ JSON",
    description: "Convert between CSV and JSON formats.",
    icon: Table,
    category: "data",
    tint: "ink",
    implemented: true,
  },
  {
    slug: "sql-format",
    name: "SQL Formatter",
    description: "Pretty print and validate SQL queries.",
    icon: Database,
    category: "data",
    tint: "ink",
    implemented: true,
  },
  // Reference
  {
    slug: "http-codes",
    name: "HTTP Status Codes",
    description: "A fast reference for all HTTP response codes.",
    icon: Activity,
    category: "reference",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "cron-explainer",
    name: "Cron Explainer",
    description: "Translate cron syntax into plain English.",
    icon: Clock,
    category: "reference",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "git-cheatsheet",
    name: "Git Cheatsheet",
    description: "Quick commands for everyday git workflows.",
    icon: GitBranch,
    category: "reference",
    tint: "rust",
    implemented: true,
  },
];

export function getTool(slug: string) {
  return tools.find((t) => t.slug === slug);
}

export function toolsByCategory(category: ToolCategory) {
  return tools.filter((t) => t.category === category);
}
