import {
  FileText,
  Scissors,
  Combine,
  Minimize2,
  FileImage,
  FileType2,
  Image as ImageIcon,
  Crop,
  Eraser,
  Palette,
  Type,
  AlignLeft,
  Hash,
  Sparkles,
  Archive,
  FileArchive,
  RefreshCw,
  Brain,
  ScanText,
  BookOpen,
  Braces,
  Binary,
  Link2,
  KeyRound,
  StickyNote, Clipboard, ListChecks, QrCode, Columns, Clock,
  Lock, Shield, Key, Database, Table, Percent, Activity, Search, GitBranch, GitCommit, Wind, Code2, Layers
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type ToolCategory =
  | "documents"
  | "images"
  | "text"
  | "ai"
  | "developer"
  | "productivity"
  | "website";

export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: ToolCategory;
  tint: "rust" | "moss" | "clay" | "ink";
  implemented?: boolean;
  acceptsFileType?: string;
  side?: "frontend" | "backend" | "both";
}

export const categories: { id: ToolCategory; label: string; blurb: string }[] =
  [
    { id: "documents", label: "Documents", blurb: "PDFs, Word, Excel" },
    { id: "images", label: "Images", blurb: "Resize, convert, clean" },
    { id: "text", label: "Text", blurb: "Edit, count, transform" },
    { id: "ai", label: "AI", blurb: "Summarize, extract" },
    { id: "developer", label: "Developer", blurb: "Encode, format" },
    { id: "productivity", label: "Productivity", blurb: "Notes, lists" },
    { id: "website", label: "Website", blurb: "Backend, design & icons" },
  ];

export const tools: Tool[] = [
  {
    slug: "title-suggester",
    name: "AI Title Suggester",
    description: "Generate catchy and relevant titles for your projects with AI.",
    icon: Sparkles,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "frontend",
  },
  {
    slug: "svg-to-jsx",
    name: "SVG → JSX",
    description: "Clean up SVGs and convert them into React components.",
    icon: Code2,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "frontend",
  },
  {
    slug: "shadow-gen",
    name: "Premium Shadow Generator",
    description: "Create smooth, multi-layered 'soft' shadows for modern UIs.",
    icon: Layers,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "frontend",
  },
  {
    slug: "css-clamp",
    name: "CSS Clamp Generator",
    description: "Create perfectly fluid typography that scales between screen sizes.",
    icon: Type,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "frontend",
  },
  {
    slug: "ai-palette",
    name: "AI Color Scout",
    description: "Generate professional color palettes from a mood or description.",
    icon: Palette,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "frontend",
  },
  {
    slug: "aspect-ratio",
    name: "Aspect Ratio",
    description: "Calculate dimensions and ratios for videos and images.",
    icon: Crop,
    category: "images",
    tint: "moss",
    implemented: true,
  },
  // Documents
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine PDFs in the order you want.",
    icon: Combine,
    category: "documents",
    tint: "rust",
    implemented: true,
    acceptsFileType: "application/pdf",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Pull pages out of a PDF into new files.",
    icon: Scissors,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce file size while keeping quality.",
    icon: Minimize2,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "pdf-to-image",
    name: "PDF → Image",
    description: "Convert each page to JPG or PNG.",
    icon: FileImage,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "word-to-pdf",
    name: "Word → PDF",
    description: "Export .docx to a clean PDF.",
    icon: FileType2,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "excel-to-pdf",
    name: "Excel → PDF",
    description: "Render spreadsheets as PDFs.",
    icon: FileText,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "pdf-to-word",
    name: "PDF → Word",
    description: "Convert PDFs back to .docx.",
    icon: FileType2,
    category: "documents",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "pdf-to-excel",
    name: "PDF → Excel",
    description: "Extract tables into spreadsheets.",
    icon: FileText,
    category: "documents",
    tint: "rust",
    implemented: true,
  },

  // Images
  {
    slug: "image-resize",
    name: "Resize image",
    description: "Set new width and height in pixels.",
    icon: Crop,
    category: "images",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "image-compress",
    name: "Compress image",
    description: "Lossy compression with a quality slider.",
    icon: Minimize2,
    category: "images",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "image-convert",
    name: "Convert format",
    description: "Switch between JPG, PNG, and WebP.",
    icon: RefreshCw,
    category: "images",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "remove-background",
    name: "Remove background",
    description: "Clean cutouts using on-device AI.",
    icon: Eraser,
    category: "images",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "image-palette",
    name: "Extract palette",
    description: "Pull dominant colors from any image.",
    icon: Palette,
    category: "images",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "favicon-gen",
    name: "Favicon Generator",
    description: "Generate favicons and manifest from one image.",
    icon: Layers,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "frontend",
  },

  // Text
  {
    slug: "case-converter",
    name: "Case converter",
    description: "UPPER, lower, Title, camelCase…",
    icon: Type,
    category: "text",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "word-counter",
    name: "Word counter",
    description: "Words, characters, reading time.",
    icon: Hash,
    category: "text",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "text-cleanup",
    name: "Text cleanup",
    description: "Strip extra spaces, line breaks, tabs.",
    icon: AlignLeft,
    category: "text",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "text-to-latex",
    name: "Text → LaTeX",
    description: "Safely escape text for LaTeX.",
    icon: BookOpen,
    category: "text",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "summarizer",
    name: "Summarizer",
    description: "Condense long passages to key points.",
    icon: Sparkles,
    category: "ai",
    tint: "clay",
    implemented: true,
  },


  // AI
  {
    slug: "ai-summarize",
    name: "AI summary",
    description: "Document → key bullets in seconds.",
    icon: Brain,
    category: "ai",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "ocr",
    name: "OCR",
    description: "Pull text out of scans and photos.",
    icon: ScanText,
    category: "ai",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "extract-content",
    name: "Content extractor",
    description: "Get clean article text from any URL.",
    icon: BookOpen,
    category: "ai",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "ai-regex-explainer",
    name: "Regex Explainer",
    description: "AI-powered breakdown of complex regular expressions.",
    icon: Search,
    category: "ai",
    tint: "rust",
    implemented: true,
  },
  {
    slug: "ai-commit-gen",
    name: "Commit Generator",
    description: "Turn your git diff into a professional commit message.",
    icon: GitCommit,
    category: "ai",
    tint: "rust",
    implemented: true,
  },

  // Developer
  {
    slug: "html-to-jsx",
    name: "HTML → JSX",
    description: "Convert HTML to React components with AI editing.",
    icon: Code2,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "frontend",
  },
  {
    slug: "css-to-tailwind",
    name: "CSS → Tailwind",
    description: "Map standard CSS to Tailwind utility classes.",
    icon: Wind,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "frontend",
  },
  {
    slug: "json-format",
    name: "JSON formatter",
    description: "Pretty print, validate, minify.",
    icon: Braces,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "both",
  },
  {
    slug: "base64",
    name: "Base64",
    description: "Encode and decode Base64 strings.",
    icon: Binary,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "url-encode",
    name: "URL encoder",
    description: "Encode and decode URL components.",
    icon: Link2,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "uuid",
    name: "UUID generator",
    description: "Create random v4 UUIDs.",
    icon: KeyRound,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "qr-generator",
    name: "QR Generator",
    description: "Create QR codes for text, URLs, and WiFi.",
    icon: QrCode,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "both",
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description: "Compare two pieces of text side by side.",
    icon: Columns,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "unix-timestamp",
    name: "Unix Timestamp",
    description: "Convert between Epoch time and dates.",
    icon: Clock,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "both",
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Write and preview markdown in real-time.",
    icon: FileText,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Create MD5, SHA-1, SHA-256 hashes.",
    icon: Shield,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "backend",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Inspect header and payload of any token.",
    icon: Key,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "both",
  },
  {
    slug: "regex-tester",
    name: "RegEx Tester",
    description: "Build and test regular expressions.",
    icon: Search,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "base64-image",
    name: "Base64 Image",
    description: "Convert images to Data URI strings.",
    icon: FileImage,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert HEX, RGB, HSL, and LCH.",
    icon: Palette,
    category: "developer",
    tint: "moss",
    implemented: true,
  },
  {
    slug: "bcrypt-generator",
    name: "Bcrypt Generator",
    description: "Hash passwords with bcrypt securely.",
    icon: Shield,
    category: "website",
    tint: "moss",
    implemented: true,
    side: "backend",
  },

  // Productivity
  {
    slug: "notes",
    name: "Quick notes",
    description: "Local notes that stay between visits.",
    icon: StickyNote,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "todo",
    name: "To-do",
    description: "A simple list. Nothing in the way.",
    icon: ListChecks,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "clipboard",
    name: "Clipboard history",
    description: "Stash snippets you reach for often.",
    icon: Clipboard,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "password-gen",
    name: "Password Generator",
    description: "Create secure, random passwords.",
    icon: Lock,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Generate placeholder text for layouts.",
    icon: FileText,
    category: "website",
    tint: "clay",
    implemented: true,
    side: "frontend",
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert between common units of measure.",
    icon: RefreshCw,
    category: "productivity",
    tint: "clay",
    implemented: true,
  },
  // Data
  {
    slug: "csv-json",
    name: "CSV ↔ JSON",
    description: "Convert between CSV and JSON formats.",
    icon: Table,
    category: "website",
    tint: "ink",
    implemented: true,
    side: "both",
  },
  {
    slug: "sql-format",
    name: "SQL Formatter",
    description: "Pretty print and validate SQL queries.",
    icon: Database,
    category: "website",
    tint: "ink",
    implemented: true,
    side: "backend",
  },
  // Reference
  {
    slug: "http-codes",
    name: "HTTP Status Codes",
    description: "A fast reference for all HTTP response codes.",
    icon: Activity,
    category: "website",
    tint: "rust",
    implemented: true,
    side: "both",
  },
  {
    slug: "cron-explainer",
    name: "Cron Explainer",
    description: "Translate cron syntax into plain English.",
    icon: Clock,
    category: "website",
    tint: "rust",
    implemented: true,
    side: "backend",
  },
  {
    slug: "git-cheatsheet",
    name: "Git Cheatsheet",
    description: "Quick commands for everyday git workflows.",
    icon: GitBranch,
    category: "developer",
    tint: "rust",
    implemented: true,
  },
];

export function getTool(slug: string) {
  return tools.find((t) => t.slug === slug);
}

export function toolsByCategory(category: ToolCategory) {
  return tools.filter((t) => t.category === category);
}
